---
apiVersion: v2
name: common
type: library
description: A common set of helper functions and templates.
version: 0.1.0
appVersion: 0.1.0
icon: https://artifacthub.io/static/media/placeholder_pkg_helm.png
home: https://github.com/daluca/helm-charts/
annotations:
  artifacthub.io/links: |-
    - name: chart
      url: https://github.com/daluca/helm-charts/tree/main/charts/common
    - name: support
      url: https://github.com/daluca/helm-charts/issues
