---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rss-bridge.fullname" . }}
  labels:
    {{- include "rss-bridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: rss-bridge
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rss-bridge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rss-bridge
  template:
    metadata:
      labels:
        {{- include "rss-bridge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rss-bridge
      annotations:
        rss-bridge-config-hash: {{ toJson .Values.rssBridge | sha256sum }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "rss-bridge.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ if .Values.image.registry }}{{ .Values.image.registry }}{{ end }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha }}{{ .Values.image.sha }}{{ end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            - name: HTTP_PORT
              value: {{ .Values.service.containerPort | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
            {{- if and .Values.rssBridge.authentication.enabled .Values.rssBridge.authentication.token }}
              path: /?action=health&token={{ .Values.rssBridge.authentication.token }}
            {{- else }}
              path: /?action=health
            {{- end }}
              port: http
            {{- if and .Values.rssBridge.authentication.enabled }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ printf "%s:%s" .Values.rssBridge.authentication.username .Values.rssBridge.authentication.password | b64enc }}
            {{- end }}
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
            {{- if and .Values.rssBridge.authentication.enabled .Values.rssBridge.authentication.token }}
              path: /?action=health&token={{ .Values.rssBridge.authentication.token }}
            {{- else }}
              path: /?action=health
            {{- end }}
              port: http
            {{- if and .Values.rssBridge.authentication.enabled }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ printf "%s:%s" .Values.rssBridge.authentication.username .Values.rssBridge.authentication.password | b64enc }}
            {{- end }}
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
            {{- if and .Values.rssBridge.authentication.enabled .Values.rssBridge.authentication.token }}
              path: /?action=health&token={{ .Values.rssBridge.authentication.token }}
            {{- else }}
              path: /?action=health
            {{- end }}
              port: http
            {{- if and .Values.rssBridge.authentication.enabled }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ printf "%s:%s" .Values.rssBridge.authentication.username .Values.rssBridge.authentication.password | b64enc }}
            {{- end }}
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/config.ini.php
              subPath: config.ini.php
              name: rss-bridge-config
      volumes:
        - name: rss-bridge-config
          configMap:
            name: {{ include "rss-bridge.fullname" . }}-config
