{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rss-bridge.fullname" . }}
  labels:
    {{- include "rss-bridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: rss-bridge
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
