---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" (include "keycloak-operator.fullname" .) "view" }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-operator
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
