---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "keycloak-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-operator.serviceAccountName" . }}
