---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.watchedSecretsControllerName" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - secrets/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
