---
doublestar: true
match_type: doublestar
gitignore_excludes: true

exclude:
  - charts/*/templates/**

formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  disallow_anchors: true
  scan_folded_as_literal: true
  pad_line_comments: 2
