---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  registry: ghcr.io
  repository: processone/eturnal
  tag: ""
  sha256: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  udp:
    port: 3478
    containerPort: 3478
  tcp:
    port: 5349
    containerPort: 5349
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: 25m
    memory: 92Mi
  limits:
    cpu: 250m
    memory: 1Gi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false
  periodSeconds: 2
  failureThreshold: 30

podSecurityContext:
  fsGroup: 9000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 9000
  runAsGroup: 9000
  runAsNonRoot: true
  privileged: false
  capabilities:
    # -- ""
    drop: [ALL]
    # -- ""
    add: [NET_BIND_SERVICE]

extraVolumeMounts: []

extraVolumes: []

# -- Name of a secret with a key containing `shared-secret`
existingSecret: ""

config:
  blacklist_clients: []
  # -- ""
  blacklist_peers: [recommended]
  credentials: {}
  # -- two transport options can be set at any given time
  # udp and either tcp, tls or auto
  # tcp is unencripted tcp
  # tls is encrypted tcp
  # auto allows for both encrypted and unencrypted tcp traffic
  listen:
    - transport: udp
    - transport: tcp
  # -- stdout make more sense as a default in containers
  # : eturnal default (log)
  log_dir: stdout
  log_level: info
  # -- Ignored by default due to being ignored when config.log_dir is set to 'stdout'
  log_rotate_count: 10
  log_rotate_size: unlimited
  max_bps: unlimited
  max_permissions: 10
  modules: {}
  # -- This option is virtually meaningless due to shared secret authentication
  realm: eturnal.net
  # relay_ipv4_addr:
  # relay_ipv6_addr:
  relay_max_port: 65535
  relay_min_port: 49152
  run_dir: run
  secret: somethingSecureIPromise
  software_name: eturnal
  strict_expiry: false
  # -- ""
  tls_ciphers: [HIGH, '!aNULL', '@STRENGTH']
  # tls_crt_file:
  # tls_dh_file:
  # tls_key_file:
  # -- ""
  tls_options: [cipher_server_preference]
  whitelist_clients: []
  whitelist_peers: []
