---
nameOverride: whisky-pig

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: example.org
      paths:
        - pathType: Prefix
          path: /
  tls:
    - secretName: example.org-tls
      hosts:
        - example.org

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: kind-testing

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits: null

persistence:
  enabled: true

config:
  prefixes:
    v4: null
    v6: fd7a:115c:a1e0::/48
  oidc:
    client_secret: somethingSecureIPromise

webui:
  enabled: true
