---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "database-migrations" }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-migrations
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ printf "%s-%s" (include "miniflux.fullname" .) "database-migrations" }}
      labels:
        {{- include "miniflux.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: database-migrations
          image: {{ if .Values.image.registry }}{{ .Values.image.registry }}{{ end }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha }}{{ .Values.image.sha }}{{ end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          command: [miniflux]
          args: [-migrate, -debug]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  {{- if and .Values.externalDatabase.enabled .Values.externalDatabase.existingSecret }}
                  name: {{ .Values.externalDatabase.existingSecret }}
                  {{- else }}
                  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "database-credentials" }}
                  {{- end }}
