---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  registry: ghcr.io
  repository: mealie-recipes/mealie
  tag: ""
  sha256: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000
  containerPort: 9000
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: false

startupProbe:
  enabled: true
  periodSeconds: 2
  failureThreshold: 30

persistence:
  enabled: false
  storageClass: ""
  size: 1Gi
  accessModes: [ReadWriteOnce]

extraEnvs: []

config:
  PUID: 65534
  PGID: 65534
  LOG_LEVEL: info
  SMTP_AUTH_STRATEGY: NONE

database:
  type: postgres
  external: false
  name: mealie
  host: localhost
  port: 5432
  username: mealie_user
  password: somethingSecureIPromise
  existingSecret: ""

postgresql:
  enabled: true
  auth:
    username: mealie
    password: mealie
    database: mealie
  service:
    ports:
      postgresql: 5432
