---
apiVersion: v2
name: rss-bridge
type: application
home: https://github.com/daluca/helm-charts/tree/main/charts/rss-bridge
sources:
  - https://github.com/RSS-Bridge/rss-bridge
version: 0.3.0
appVersion: "2023-09-24"
description: The RSS feed for websites missing it
dependencies:
  - name: memcached
    version: ">=6.0.0 <7.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: memcached.enabled
