---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: eturnal
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: eturnal
  ports:
    {{- range $listen := .Values.config.listen }}
    - name: {{ printf "stunturn-%s" (ternary "udp" "tcp" (eq $listen.transport "udp")) }}
      port: {{ ternary (default $.Values.service.udp.containerPort $.Values.service.udp.port) (default $.Values.service.tcp.containerPort $.Values.service.tcp.port) (eq $listen.transport "udp") }}
      targetPort: {{ printf "stunturn-%s" (ternary "udp" "tcp" (eq $listen.transport "udp")) }}
      protocol: {{ ternary "UDP" "TCP" (eq $listen.transport "udp") }}
    {{- end }}
