{{- if and .Values.admin.create (not .Values.admin.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin-credentials" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
type: kubernetes.io/basic-auth
data:
  username: {{ default "admin" .Values.admin.username | b64enc }}
  password: {{ default (randAlphaNum 32) .Values.admin.password | b64enc }}
{{- end }}
