{{- if not (or (eq "sqlite" .Values.database.type) (and .Values.database.external .Values.database.existingSecret)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "synapse.fullname" .) "database-credentials" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
type: Opaque
stringData:
  database.yaml: |
    database:
      args:
        user: {{ if .Values.database.external }}{{ .Values.database.username }}{{ else }}{{ .Values.postgresql.auth.username }}{{ end }}
        password: {{ if .Values.database.external }}{{ .Values.database.password }}{{ else }}{{ .Values.postgresql.auth.password }}{{ end }}
{{- end }}
