{{- if not (or (eq "sqlite" .Values.database.type) (and .Values.database.external .Values.database.existingSecret)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "synapse.fullname" .) "database-credentials" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
type: Opaque
stringData:
  database.yaml: |
    database:
      name: psycopg2
      args:
        user: {{ .Values.database.username }}
        password: {{ .Values.database.password }}
        database: {{ .Values.database.name }}
        {{- if .Values.database.external }}
        host: {{ .Values.database.host }}
        {{- else }}
        host: {{ printf "%s-%s" .Release.Name "postgresql" }}
        {{- end }}
        port: {{ .Values.database.port }}
        {{- with .Values.database.arguments }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
