---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: synapse
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: synapse
      annotations:
        synapse-config-hash: {{ toJson .Values.homeserver | sha256sum }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "common.vimage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [python3, -m, synapse.app.homeserver]
          args:
            - --config-path=/synapse/homeserver.yaml
            - --config-path=/synapse/homeserver.d/
            - --config-directory=/synapse/
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- with omit .Values.readinessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /health
              port: http
          {{- with omit .Values.startupProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /synapse/homeserver.yaml
              subPath: homeserver.yaml
              name: synapse-config
            - mountPath: /synapse/
              subPath: root
              name: synapse-data
            {{- if .Values.mediaStore.enabled }}
            - mountPath: {{ .Values.mediaStore.path }}
              subPath: media
              name: synapse-data
            {{- end }}
            - mountPath: /synapse/homeserver.d/
              name: config-data
            - mountPath: /synapse/homeserver.d/secrets.yaml
              subPath: secrets.yaml
              name: synapse-secrets
            - mountPath: /synapse/logging.yaml
              subPath: logging.yaml
              name: synapse-config
            {{- if .Values.signingKey.enabled }}
            - mountPath: {{ printf "/synapse/%s.key" .Values.homeserver.server_name }}
              subPath: signing.key
              name: signing-key
            {{- end }}
            {{- if .Values.appServices.doublepuppet.enabled }}
            - mountPath: /synapse/appservices/double-puppeting-registration.yaml
              subPath: registration.yaml
              name: synapse-double-puppet-secrets
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if any (eq "postgresql" .Values.database.type) .Values.extraMergeVolumeMounts }}
      initContainers:
        - name: merge-config
          image: docker.io/mikefarah/yq:4.44.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [merge.sh]
          volumeMounts:
            - mountPath: /usr/local/bin/merge.sh
              subPath: merge.sh
              name: scripts
            - mountPath: /target
              name: config-data
            {{- if eq "postgresql" .Values.database.type }}
            - mountPath: /workdir/config/database.yaml
              subPath: database.yaml
              name: synapse-config
            - mountPath: /workdir/secrets/database.yaml
              subPath: database.yaml
              name: database-credentials
            {{- end }}
            {{- with .Values.extraMergeVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- end }}
      volumes:
        - name: synapse-config
          configMap:
            name: {{ printf "%s-config" (include "common.fullname" .) }}
        - name: synapse-secrets
          secret:
            secretName: {{ printf "%s-secrets" (include "common.fullname" .) }}
        {{- if not (eq "sqlite" .Values.database.type) }}
        - name: database-credentials
          secret:
            {{- if and .Values.database.external .Values.database.existingSecret }}
            secretName: {{ .Values.database.existingSecret }}
            {{- else }}
            secretName: {{ printf "%s-database-credentials" (include "common.fullname" .) }}
            {{- end }}
        {{- end }}
        - name: synapse-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-data" (include "common.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.signingKey.enabled }}
        - name: signing-key
          secret:
            {{- if .Values.signingKey.existingSecret }}
            secretName: {{ .Values.signingKey.existingSecret }}
            {{- else }}
            secretName: {{ printf "%s-signing-key" (include "common.fullname" .) }}
            {{- end }}
        {{- end }}
        {{- if any (eq "postgresql" .Values.database.type) }}
        - name: scripts
          configMap:
            name: {{ printf "%s-scripts" (include "common.fullname" .) }}
            defaultMode: 0777
        {{- end }}
        - name: config-data
          emptyDir: {}
        {{- if .Values.appServices.doublepuppet.enabled }}
        - name: synapse-double-puppet-secrets
          secret:
            {{- if .Values.appServices.doublepuppet.existingSecret }}
            secretName: {{ .Values.appServices.doublepuppet.existingSecret }}
            {{- else }}
            secretName: {{ printf "%s-double-puppet-config" (include "common.fullname" .) }}
            {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
