{{- if and .Values.appServices.doublepuppet.enabled (not .Values.appServices.doublepuppet.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-double-puppet-config" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
stringData:
  registration.yaml: |-
    # The ID doesn't really matter, put whatever you want.
    id: doublepuppet
    # The URL is intentionally left empty (null), as the homeserver shouldn't
    # push events anywhere for this extra appservice. If you use a
    # non-spec-compliant server, you may need to put some fake URL here.
    url:
    # Generate random strings for these three fields. Only the as_token really
    # matters, hs_token is never used because there's no url, and the default
    # user (sender_localpart) is never used either.
    as_token: {{ default (randAlphaNum 64) .Values.appServices.doublepuppet.as_token }}
    hs_token: {{ default (randAlphaNum 64) .Values.appServices.doublepuppet.hs_token }}
    sender_localpart: {{ default (randAlphaNum 32) .Values.appServices.doublepuppet.sender_localpart }}
    # Bridges don't like ratelimiting. This should only apply when using the
    # as_token, normal user tokens will still be ratelimited.
    rate_limited: false
    namespaces:
      users:
      # Replace your\.domain with your server name (escape dots for regex)
      - regex: {{ printf "@.*:%s" (join "\\." (splitList "." .Values.homeserver.server_name)) | squote }}
        # This must be false so the appservice doesn't take over all users completely.
        exclusive: false
{{- end }}
