{{- if .Values.ingress.enabled -}}
{{- $fullName := include "synapse.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ printf "%s-%s" .Values.ingress.host "tls" }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /_matrix
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
          - path: /_synapse/client
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
