{{- if not .Values.homeserver.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "synapse.fullname" .) "secrets" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yaml: |-
    macaroon_secret_key: {{ default (randAlphaNum 50) .Values.homeserver.macaroon_secret_key }}
    registration_shared_secret: {{ default (randAlphaNum 50) .Values.homeserver.registration_shared_secret }}
    form_secret: {{ default (randAlphaNum 50) .Values.homeserver.form_secret }}
{{- end }}
