{{- if and .Values.signingKey.enabled (not .Values.signingKey.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-signing-key" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
type: Opaque
data:
  signing.key: {{ printf "%s\n" .Values.signingKey.key | b64enc }}
{{- end }}
