---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-envs" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mealie
data:
  {{- range $key, $value := omit .Values.config }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
