{{- if not (or (eq "sqlite" .Values.database.type) (and .Values.database.external .Values.database.existingSecret)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database-credentials" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mealie
type: kubernetes.io/basic-auth
data:
  username: {{ ternary .Values.database.username .Values.postgresql.auth.username .Values.database.external | b64enc }}
  password: {{ ternary .Values.database.password .Values.postgresql.auth.password .Values.database.external | b64enc }}
{{- end }}
