{{- if and (not .Values.existingSecret) (and .Values.config.OIDC_CLIENT_ID .Values.config.OIDC_CLIENT_SECRET) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-envs" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mealie
type: Opaque
data:
  OIDC_CLIENT_ID: {{ .Values.config.OIDC_CLIENT_ID | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.config.OIDC_CLIENT_SECRET | b64enc }}
{{- end }}
