{{- if .Values.delegation.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "synapse.wellKnownFullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: delegation
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.homeserver.server_name }};

        access_log /dev/stdout;

        location = /healthz {
            {{- if not .Values.delegation.nginx.logHealthCheck }}
            access_log off;
            {{- end }}
            return 200 'OK';
        }

        location ^~ /.well-known/matrix {
            default_type {{ .Values.delegation.nginx.defaultType | squote }};
            {{- if .Values.delegation.nginx.cors.enabled }}
            add_header 'Access-Control-Allow-Origin' {{ .Values.delegation.nginx.cors.origin | squote }};
            add_header 'Access-Control-Allow-Headers' {{ .Values.delegation.nginx.cors.headers | squote }};
            add_header 'Access-Control-Allow-Methods' {{ .Values.delegation.nginx.cors.methods | upper | squote }};
            {{- end }}

            location /.well-known/matrix/server {
                return 200 '{ "m.server": "{{ $.Values.ingress.host }}:443" }\n';
            }

            location /.well-known/matrix/client {
                {{- if .Values.delegation.slidingSync.enabled }}
                return 200 '{ "m.homeserver": {"base_url": "https://{{ $.Values.ingress.host }}"}, "org.matrix.msc3575.proxy": {"url": {{ .Values.delegation.slidingSync.host | quote }}}, "m.identity_server": {"base_url": "https://vector.im"} }\n\n';
                {{- else }}
                return 200 '{ "m.homeserver": {"base_url": "https://{{ $.Values.ingress.host }}"}, "m.identity_server": {"base_url": "https://vector.im"} }\n\n';
                {{- end }}
            }
        }
    }
{{- end }}
