{{- if .Values.delegation.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "synapse.wellKnownFullname" .) "config" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: delegation
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.homeserver.server_name }};

        access_log /dev/stdout;

        location = /healthz {
            {{- if .Values.delegation.ngnix.logHealthCheck }}
            access_log off;
            {{- end }}

            return 200 'OK';
        }

        location ^~ /.well-known/matrix {
            default_type {{ .Values.delegation.ngnix.defaultType }};
            {{- .Values.delegation.ngnix.cors.enabled }}
            add_header Access-Control-Allow-Origin {{ .Values.delegation.ngnix.cors.origin }};
            add_header Access-Control-Allow-Headers {{ .Values.delegation.ngnix.cors.headers }}
            add_header Access-Control-Allow-Methods {{ .Values.delegation.ngnix.cors.methods | upper }}
            {{- end }}

            location /.well-known/matrix/server {
                return 200 '{ "m.server": "{{ $.Values.ingress.host }}:443" }\n';
            }

            location /.well-known/matrix/client {
                return 200 '{ "m.homeserver": {"base_url": "https://matrix.{{ .Values.homeserver.server_name }}"}, "m.identity_server": {"base_url": "https://vector.im"} }\n\n';
            }
        }
    }
{{- end }}
