{{- if .Values.delegation.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "synapse.wellKnownFullname" .) "config" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: delegation
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.homeserver.server_name }};

        access_log /dev/stdout;

        location = /healthz {
            access_log off;

            return 200 'OK';
        }

        location ^~ /.well-known/matrix {
            default_type application/json;

            location /.well-known/matrix/server {
                return 200 '{ "m.server": "{{ $.Values.ingress.host }}:443" }\n';
            }

            location /.well-known/matrix/client {
                return 200 '{ "m.homeserver": {"base_url": "https://matrix.korero.dev"}, "m.identity_server": {"base_url": "https://vector.im"} }\n\n';
            }
        }
    }
  server.json: |
    { "m.server": "matrix.{{ .Values.ingress.host }}:443" }
{{- end }}
