---
apiVersion: v2
name: keycloak-operator
type: application
description: >-
  Open source Identity and Access Management for modern applications and
  services
version: 0.3.4
appVersion: 24.0.3
kubeVersion: ">=1.19.0"
icon: https://www.keycloak.org/resources/images/icon.svg
home: https://www.keycloak.org
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/keycloak-operator
  - https://github.com/keycloak/keycloak/tree/main/operator
  - https://github.com/keycloak/keycloak
  - https://github.com/keycloak/keycloak-k8s-resources
annotations:
  artifacthub.io/crds: |-
    - kind: Keycloak
      version: v2alpha1
      name: keycloak
      displayName: Keycloak
      description: Keycloak cluster to be created
    - kind: KeycloakRealmImport
      version: v2alpha1
      name: keycloakrealmimport
      displayName: Keycloak Realm Import
      description: Keycloak realm which will be imported initially
  artifacthub.io/crdsExamples: |-
    - apiVersion: k8s.keycloak.org/v2alpha1
      kind: Keycloak
      metadata:
        name: example-kc
      spec:
        instances: 1
        db:
          vendor: postgres
          host: postgres-db
          usernameSecret:
            name: keycloak-db-secret
            key: username
          passwordSecret:
            name: keycloak-db-secret
            key: password
        http:
          tlsSecret: example-tls-secret
        hostname:
          hostname: test.keycloak.org
    - apiVersion: k8s.keycloak.org/v2alpha1
      kind: KeycloakRealmImport
      metadata:
        name: my-realm-kc
      spec:
        keycloakCRName: example-kc
        realm:
          enabled: true
          realm: example
          displayName: Example
  artifacthub.io/images: |-
    - name: keycloak-operator
      image: quay.io/keycloak/keycloak:24.0.3
      platforms:
        - linux/amd64
        - linux/arm64
    - name: keycloak
      image: quay.io/keycloak/keycloak-operator:24.0.3
      platforms:
        - linux/amd64
  artifacthub.io/links: |-
    - name: chart
      url: https://github.com/daluca/helm-charts/tree/main/charts/keycloak-operator
    - name: operator
      url: https://github.com/keycloak/keycloak/tree/main/operator
    - name: application
      url: https://github.com/keycloak/keycloak
    - name: crds
      url: https://github.com/keycloak/keycloak-k8s-resources
    - name: support
      url: https://github.com/daluca/helm-charts/issues
  artifacthub.io/operator: "true"
