---
apiVersion: v2
name: keycloak-operator
type: application
home: https://www.keycloak.org
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/keycloak-operator
  - https://github.com/keycloak/keycloak/tree/main/operator
  - https://github.com/keycloak/keycloak
  - https://github.com/keycloak/keycloak-k8s-resources
version: 0.1.1
appVersion: 22.0.5
description: >-
  Open source Identity and Access Management for modern applications and
  services
