---
nameOverride: ""
fullnameOverride: ""

openshift: false

replicaCount: 1

image:
  registry: quay.io
  repository: keycloak/keycloak-operator
  tag: ""
  sha256: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources: {}

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
  periodSeconds: 2
  failureThreshold: 15

keycloakImage:
  registry: quay.io
  repository: keycloak/keycloak
  tag: ""
  # linux-x86_64 default image sha as a work-around for nightly image being pulled
  sha256: 050b5430f5a2f417ef41dd5ccdda70f900761bb757d08a17dd6957796e61acc9
