---
nameOverride: ""
fullnameOverride: ""

openshift: false

replicaCount: 1

image:
  registry: quay.io
  repository: keycloak/keycloak-operator
  tag: ""
  sha256: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080
  annotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  limits:
    cpu: 700m
    memory: 450Mi
  requests:
    cpu: 300m
    memory: 450Mi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
  periodSeconds: 2
  failureThreshold: 15

keycloakImage:
  registry: quay.io
  repository: keycloak/keycloak
  tag: ""
  sha256: ""
