---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ntfy
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ntfy
      annotations:
        ntfy-config-hash: {{ toJson .Values.config | sha256sum }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "common.vimage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
            - --config=/etc/ntfy/server.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
          {{- with omit .Values.readinessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /v1/health
              port: http
          {{- with omit .Values.startupProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/ntfy/server.yaml
              subPath: server.yaml
              name: ntfy-config
            - mountPath: /var/cache/ntfy
              subPath: cache
              name: ntfy-data
            - mountPath: /var/lib/ntfy
              subPath: lib
              name: ntfy-data
      volumes:
        - name: ntfy-config
          configMap:
            name: {{ printf "%s-config" (include "common.fullname" .) }}
        {{- if not .Values.persistence.enabled }}
        - name: ntfy-data
          emptyDir: {}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: ntfy-data
      spec:
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . }}
        {{- end }}
  {{- end }}
