{{- if and (.Values.admin.enabled) (not .Values.admin.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . | trunc 57 | trimSuffix "-" }}-admin
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.admin.username | b64enc }}
  password: {{ .Values.admin.password | b64enc }}
{{- end }}
