---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "cleanup-tasks" }}
  labels:
    app.kubernetes.io/component: cleanup-tasks
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  schedule: "43 16 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ printf "%s-%s" (include "miniflux.fullname" .) "cleanup-tasks" }}
          labels:
            {{- include "miniflux.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cleanup-tasks
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-tasks
              image: {{ if .Values.image.registry }}{{ .Values.image.registry }}{{ end }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha }}{{ .Values.image.sha }}{{ end }}
              imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
              command: [miniflux]
              args: [-run-cleanup-tasks, -debug]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_URL
                      {{- if and .Values.externalDatabase.enabled .Values.externalDatabase.existingSecret }}
                      name: {{ .Values.externalDatabase.existingSecret }}
                      {{- else }}
                      name: {{ printf "%s-%s" (include "miniflux.fullname" .) "database-credentials" }}
                      {{- end }}
