---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniflux.fullname" . | trunc 56 | trimSuffix "-" }}-config
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: 0.0.0.0:{{ .Values.service.containerPort }}
  HTTP_CLIENT_USER_AGENT: Mozilla/5.0 (compatible; Miniflux/{{ default .Chart.AppVersion .Values.image.tag }}; +https://miniflux.app)
  {{- with omit .Values.config "LISTEN_ADDR" "HTTP_CLIENT_USER_AGENT" "RUN_MIGRATIONS" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
