{{- if not (and .Values.database.external .Values.database.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "database-credentials" }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
    app.kubernetes.io/component: miniflux
type: Opaque
data:
  {{- if .Values.database.external }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" .Values.database.username .Values.database.password .Values.database.host (.Values.database.port | toString) .Values.database.name | b64enc }}
  {{- else }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password (printf "%s-%s" .Release.Name "postgresql") (.Values.postgresql.service.ports.postgresql | toString) .Values.postgresql.auth.database | b64enc }}
  {{- end }}
{{- end }}
