{{- if not (and .Values.externalDatabase.enabled .Values.externalDatabase.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . | trunc 42 | trimSuffix "-" }}-database-credentials
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://miniflux:password@%s:5432/miniflux?sslmode=disable" (printf "%s-%s" .Release.Name "postgresql") | b64enc }}
  {{- else if .Values.externalDatabase.url }}
  DATABASE_URL: {{ .Values.externalDatabase.url | b64enc }}
  {{- end }}
{{- end }}
