---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "refresh-feeds" }}
  labels:
    app.kubernetes.io/component: refresh-feeds
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  schedule: "12 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ printf "%s-%s" (include "miniflux.fullname" .) "refresh-feeds" }}
          labels:
            {{- include "miniflux.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: refresh-feeds
        spec:
          restartPolicy: OnFailure
          containers:
            - name: refresh-feeds
              image: {{ if .Values.image.registry }}{{ .Values.image.registry }}{{ end }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha }}{{ .Values.image.sha }}{{ end }}
              imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
              command: [miniflux]
              args: [-refresh-feeds, -debug]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_URL
                      {{- if and .Values.externalDatabase.enabled .Values.externalDatabase.existingSecret }}
                      name: {{ .Values.externalDatabase.existingSecret }}
                      {{- else }}
                      name: {{ include "miniflux.fullname" . | trunc 42 | trimSuffix "-" }}-database-credentials
                      {{- end }}
