---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . | trunc 55 | trimSuffix "-" }}-secrets
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := omit .Values.secrets "DATABASE_URL" }}
  {{ printf "%s: %s" $key ($value | b64enc) }}
  {{- end }}
