---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . | trunc 55 | trimSuffix "-" }}-secrets
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://miniflux:password@%s:5432/miniflux?sslmode=disable" (printf "%s-postgresql" (include "miniflux.fullname" .)) | b64enc }}
  {{- else }}
  DATABASE_URL: {{ .Values.database.url | b64enc }}
  {{- end }}
  {{- range $key, $value := omit .Values.secrets "DATABASE_URL" }}
  {{ printf "%s: %s" $key ($value | b64enc) }}
  {{- end }}
