{{- if .Values.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "miniflux.fullname" .) "secrets" }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
    app.kubernetes.io/component: miniflux
type: Opaque
data:
  {{- range $key, $value := omit .Values.secrets "DATABASE_URL" }}
  {{ printf "%s: %s" $key ($value | b64enc) }}
  {{- end }}
{{- end }}
