---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflux.fullname" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
    app.kubernetes.io/component: miniflux
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app.kubernetes.io/component: frontend
    {{- include "miniflux.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ default .Values.service.containerPort .Values.service.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflux.fullname" . | trunc 55 | trimSuffix "-" }}-scheduler
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app.kubernetes.io/component: backend
    {{- include "miniflux.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ default .Values.service.containerPort .Values.service.port }}
      targetPort: http
      protocol: TCP
