---
apiVersion: v2
name: synapse
type: application
description: Matrix homeserver written in Python/Twisted
version: 0.6.0
appVersion: 1.100.0
kubeVersion: ">=1.19.0-0"
icon: https://matrix.org/images/matrix-favicon.svg
home: https://github.com/matrix-org/synapse
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/synapse
dependencies:
  - name: postgresql
    version: ">=13.0.0 <14.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
annotations:
  artifacthub.io/alternativeName: matrix-synapse
  artifacthub.io/images: |-
    - name: synapse
      image: ghcr.io/matrixdotorg/synapse:v1.100.0
      platforms:
        - linux/amd64
        - linux/arm64
    - name: postgresql
      image: bitnami/postgresql:16.1.0-debian-11-r9
      platforms:
        - linux/amd64
        - linux/arm64
    - name: nginx
      image: nginx:1.25.3-alpine
      platforms:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
        - linux/ppc64le
        - linux/s390x
    - name: yq
      image: mikefarah/yq:4.40.3
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
  artifacthub.io/links: |-
    - name: chart
      url: https://github.com/daluca/helm-charts/tree/main/charts/synapse
    - name: source
      url: https://github.com/matrix-org/synapse
    - name: support
      url: https://github.com/daluca/helm-charts/issues
