---
apiVersion: v2
name: synapse
type: application
description: Matrix homeserver written in Python/Twisted
version: 0.11.1
appVersion: 1.105.1
kubeVersion: ">=1.19.0-0"
icon: https://matrix.org/images/matrix-favicon.svg
home: https://github.com/element-hq/synapse
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/synapse
dependencies:
  - name: postgresql
    version: ">=15.0.0 <16.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
annotations:
  artifacthub.io/alternativeName: matrix-synapse
  artifacthub.io/images: |-
    - name: synapse
      image: ghcr.io/element-hq/synapse:v1.105.1
      platforms:
        - linux/amd64
        - linux/arm64
    - name: postgresql
      image: docker.io/bitnami/postgresql:16.2.0-debian-12-r15
      platforms:
        - linux/amd64
        - linux/arm64
    - name: nginx
      image: docker.io/nginx:1.25.4-alpine
      platforms:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
        - linux/ppc64le
        - linux/s390x
    - name: yq
      image: docker.io/mikefarah/yq:4.43.1
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
  artifacthub.io/links: |-
    - name: chart
      url: https://github.com/daluca/helm-charts/tree/main/charts/synapse
    - name: source
      url: https://github.com/element-hq/synapse
    - name: support
      url: https://github.com/daluca/helm-charts/issues
