---
nameOverride: whisky-pig

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: kind-testing

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits: null

livenessProbe:
  enabled: true

startupProbe:
  enabled: true

config:
  listen:
    - transport: udp
    - transport: auto
      enable_turn: false
  log_level: debug
  modules:
    mod_log_stun:
      level: debug
    mod_stats_prometheus:
      vm_metrics: false
  relay_max_port: 50100
  relay_min_port: 50001
