{{- if .Values.admin.create -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "synapse.fullname" .) "create-admin" }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ printf "%s-%s" (include "synapse.fullname" .) "create-admin" }}
      labels:
        app.kubernetes.io/component: backend
        {{- include "synapse.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-admin
          image: {{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ default (printf "v%s" .Chart.AppVersion) .Values.image.tag }}{{ if .Values.image.sha256 }}@sha256:{{ .Values.image.sha256 }}{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [register_new_matrix_user]
          args:
            - --admin
            - --user
            - "$(ADMIN_USERNAME)"
            - --password
            - "$(ADMIN_PASSWORD)"
            - --config
            - /synapse/homeserver.d/secrets.yaml
            - http://{{ include "synapse.fullname" . }}{{ if ne 80.0 (default .Values.service.containerPort .Values.service.port) }}:{{ default .Values.service.containerPort .Values.service.port }}{{ end }}
          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  {{- if .Values.admin.existingSecret }}
                  name: {{ .Values.admin.existingSecret }}
                  {{- else }}
                  name: {{ printf "%s-%s" (include "synapse.fullname" .) "admin-credentials" }}
                  {{- end }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  {{- if .Values.admin.existingSecret }}
                  name: {{ .Values.admin.existingSecret }}
                  {{- else }}
                  name: {{ printf "%s-%s" (include "synapse.fullname" .) "admin-credentials" }}
                  {{- end }}
          volumeMounts:
            - mountPath: /synapse/homeserver.d/secrets.yaml
              subPath: secrets.yaml
              name: synapse-secrets
      volumes:
        - name: synapse-secrets
          secret:
            secretName: {{ printf "%s-%s" (include "synapse.fullname" .) "secrets" }}
{{- end }}
