---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak-operator
  template:
    metadata:
      labels:
        {{- include "keycloak-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak-operator
    spec:
      serviceAccountName: {{ include "keycloak-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha256 }}@sha256:{{ .Values.image.sha256 }}{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: {{ if .Values.keycloakImage.registry }}{{ .Values.keycloakImage.registry }}/{{ end }}{{ .Values.keycloakImage.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.keycloakImage.sha256 }}@sha256:{{ .Values.keycloakImage.sha256 }}{{ end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
              scheme: HTTP
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
              scheme: HTTP
          {{- with omit .Values.readinessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /q/health/started
              port: http
              scheme: HTTP
          {{- with omit .Values.startupProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
