---
apiVersion: v2
name: headscale
type: application
description: >-
  An open source, self-hosted implementation of the Tailscale control server
version: 0.1.1
appVersion: 0.23.0-alpha12
kubeVersion: ">=1.19.0-0"
icon: https://raw.githubusercontent.com/juanfont/headscale/main/docs/logo/headscale3-dots.png
home: https://headscale.net/
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/headscale
dependencies:
  - name: common
    version: ">=0.1.0 <0.2.0"
    repository: oci://ghcr.io/daluca/charts
  - name: postgresql
    version: ">=15.0.0 <16.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
annotations:
  artifacthub.io/images: |-
    - name: headscale
      image: ghcr.io/juanfont/headscale:v0.23.0-alpha12
      platforms:
        - linux/amd64
        - linux/arm64
    - name: headscale-web-ui
      image: docker.io/goodieshq/headscale-admin:0.1.12b
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/links: |-
    - name: chart
      url: https://github.com/daluca/helm-charts/tree/main/charts/headscale
    - name: source
      url: https://github.com/juanfont/headscale
    - name: source
      url: https://github.com/GoodiesHQ/headscale-admin
    - name: support
      url: https://github.com/daluca/helm-charts/issues
