{{- if .Values.webui.ingress.enabled -}}
{{- $fullname := include "web-ui.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
  {{- with .Values.webui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webui.ingress.className }}
  ingressClassName: {{ .Values.webui.ingress.className }}
  {{- end }}
  {{- if .Values.webui.ingress.tls }}
  tls:
    {{- range .Values.webui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webui.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullname }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
