{{- if .Values.webui.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
  {{- with .Values.webui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webui.service.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
  ports:
    - port: {{ default .Values.webui.service.containerPort .Values.webui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
