---
config:
  LOG_LEVEL: debug

postgresql:
  image:
    tag: 14
  primary:
    extraEnvVars:
      # TODO: Remove when upstream resolves issue
      #
      # Workaround to start container normally
      # https://github.com/bitnami/containers/issues/74788
      - name: POSTGRESQL_REPLICATION_USE_PASSFILE
        value: "false"
