---
apiVersion: v2
name: miniflux
type: application
home: https://github.com/daluca/helm-charts/tree/main/charts/miniflux
sources:
  - https://github.com/miniflux/v2
version: 0.3.2
appVersion: 2.0.49
description: Minimalist and opinionated feed reader
dependencies:
  - name: postgresql
    version: ">=12.0.0 <13.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
