---
apiVersion: v2
name: miniflux
type: application
home: https://miniflux.app
sources:
  - https://github.com/daluca/helm-charts/tree/main/charts/miniflux
  - https://github.com/miniflux/v2
version: 0.4.4
appVersion: 2.0.50
description: Minimalist and opinionated feed reader
dependencies:
  - name: postgresql
    version: ">=12.0.0 <13.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
