---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  registry: docker.io
  repository: miniflux/miniflux
  tag: ""
  sha: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  hosts: []

serviceAccount:
  create: true
  annotations: {}

resources:
  requests:
    cpu: 25m
    memory: 92Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
  periodSeconds: 2
  failureThreshold: 15

config:
  WATCHDOG: "false"

secrets: {}
existingSecret: ""

admin:
  username: admin
  password: password
  existingSecret: ""

database:
  # -- (string)
  url: null

postgresql:
  enabled: true
  primary:
    initdb:
      scripts:
        miniflux.sql: |-
          CREATE EXTENSION hstore;
          CREATE USER miniflux WITH ENCRYPTED PASSWORD 'password';
          CREATE DATABASE miniflux WITH OWNER miniflux;
