---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  registry: docker.io
  repository: miniflux/miniflux
  tag: ""
  sha: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  hosts: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: 25m
    memory: 92Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
  periodSeconds: 2
  failureThreshold: 15

cronJobs:
  # -- Runs every hour on the hour
  refreshFeedsSchedule: 0 * * * *
  # -- Runs every day at 2:30am UTC
  cleanupTasksSchedule: 30 2 * * *

config:
  POLLING_FREQUENCY: "60"
  WATCHDOG: "false"

secrets: {}
existingSecret: ""

admin:
  enabled: true
  username: admin
  password: password
  existingSecret: ""

database:
  external: false
  name: miniflux_db
  host: localhost
  port: 5432
  username: miniflux_user
  password: somethingSecureIPromise
  existingSecret: ""

postgresql:
  enabled: true
  auth:
    username: miniflux
    password: miniflux
    database: miniflux
  primary:
    initdb:
      scripts:
        miniflux.sql: |-
          CREATE EXTENSION hstore;
  service:
    ports:
      postgresql: 5432
