---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adminer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adminer.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "adminer.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}{{ if .Values.image.sha }}@{{ .Values.image.sha }}{{ end }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            {{- if .Values.theme }}
            - name: ADMINER_DESIGN
              value: {{ .Values.theme }}
            {{- end }}
            {{- if and .Values.defaultServerType (not .Values.plugins.loginServers) }}
            - name: ADMINER_DEFAULT_SERVER
              value: {{ .Values.defaultServerType }}
            {{- end }}
            {{- if and .Values.plugins.enabled .Values.plugins.list }}
            - name: ADMINER_PLUGINS
              value: {{ join " " .Values.plugins.list }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{- with omit .Values.livenessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with omit .Values.readinessProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: http
          {{- with omit .Values.startupProbe "enabled" }}
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and .Values.plugins.enabled .Values.plugins.loginServers }}
          volumeMounts:
            - mountPath: /var/www/html/plugins-enabled/login-servers.php
              subPath: login-servers.php
              name: plugins-config
          {{- end }}
      {{- if and .Values.plugins.enabled .Values.plugins.loginServers }}
      volumes:
        - name: plugins-config
          configMap:
            name: {{ include "adminer.fullname" . | trunc 48 }}-plugins-config
      {{- end }}
