---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    {{- include "adminer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ default .Values.service.containerPort .Values.service.port }}
      targetPort: http
      protocol: TCP
