{{- if .Values.linkwarden.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config-envs" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: linkwarden
data:
  {{- range $key, $value := .Values.linkwarden.config }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
{{- end -}}
