{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database-credential-envs" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: linkwarden
type: Opaque
data:
  {{- if and .Values.database.external (not .Values.database.existingSecret) }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.database.username .Values.database.password .Values.database.host (toString .Values.database.port) .Values.database.name | b64enc }}
  {{- else }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (printf "%s-postgresql.%s" (include "common.fullname" .) .Release.Namespace) (toString .Values.postgresql.service.ports.postgresql) .Values.postgresql.auth.database | b64enc }}
  {{- end }}
{{- end -}}
