{{- if and (not .Values.linkwarden.existingSecret) .Values.linkwarden.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-envs" (include "common.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: linkwarden
type: Opaque
data:
  {{- range $key, $value := .Values.linkwarden.secrets }}
  {{ $key }}: {{ quote $value | b64enc }}
  {{- end }}
{{- end -}}
