---
name: Scheduled Testing

on:
  schedule: [cron: 45 14 * * *]

  workflow_dispatch: {}

permissions:
  contents: read

env:
  CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
  YAMLLINT_VERSION: 1.33.0

jobs:
  testing:
    name: charts
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        kubernetes_version: [1.27.13, 1.28.9, 1.29.4, 1.30.2]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup chart testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          yamllint_version: ${{ env.YAMLLINT_VERSION }}

      - name: lint ${{ matrix.chart }} chart
        run: ct lint --config ct.yaml --print-config --debug --all --exclude-deprecated

      - name: check for application chart
        id: chart-type
        run: echo "type=$(yq '.type' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: create kind cluster
        if: steps.chart-type.outputs.type == 'application'
        uses: helm/kind-action@v1.9.0
        with:
          node_image: kindest/node:v${{ matrix.kubernetes_version }}
          config: kind/multi-node-cluster.yaml

      - name: install ${{ matrix.chart }} chart
        if: steps.chart-type.outputs.type == 'application'
        run: ct install --config ct.yaml --print-config --debug --all --exclude-deprecated
