---
name: Scheduled Testing

on:
  schedule: [cron: 45 14 * * *]

  workflow_dispatch: {}

permissions:
  contents: read

env:
  CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
  YAMLLINT_VERSION: 1.33.0

jobs:
  testing:
    name: charts
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        kubernetes_version: [1.26.6, 1.27.3, 1.28.0]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup chart testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          yamllint_version: ${{ env.YAMLLINT_VERSION }}

      - name: lint ${{ matrix.chart }} chart
        run: ct lint --config ct.yaml --print-config --debug --all --exclude-deprecated

      - name: create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:v${{ matrix.kubernetes_version }}

      - name: install ${{ matrix.chart }} chart
        run: ct install --config ct.yaml --print-config --debug --all --exclude-deprecated
