---
name: Charts

on:
  push:
    branches: [main]
    paths: [charts/**]

  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        chart:
          - adminer

    defaults:
      run:
        working-directory: charts/${{ matrix.chart }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: helm login
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: chart info
        run: |
          echo "CHART_NAME=$(yq '.name' Chart.yaml)" >> $GITHUB_ENV
          echo "CHART_VERSION=$(yq '.version' Chart.yaml)" >> $GITHUB_ENV

      - name: helm package
        run: helm package .

      - name: helm push
        run: helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
